spring:
  application:
    name: BankingMangPro2
  datasource:
    url: jdbc:postgresql://localhost:5432/dims_db
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
